### PR TITLE
Properly disable gateway controller in SD-only install

### LINKED ISSUE #936: service discovery not working without gateways
**What happened**:

I deployed solely the lighthouse agents (no gateways) for service discovery by : 

`subctl deploy-broker --components service-discovery`

I followed the user-guide and deployed the nginx-test pods.
https://submariner.io/operations/usage/

The following connectivity test results in an `unknown host exception` when the deployment on the local cluster is scaled to zero: 

`curl nginx.nginx-test.svc.clusterset.local:8080`.

**What you expected to happen**:

Since the local cluster is not responding, I expect a response from the remote cluster.

Enable debug logging on the lighthouse coredns pods for more specific logging.

```
[DEBUG] plugin/lighthouse: Request received for "nginx.nginx-test.svc.clusterset.local."
[DEBUG] plugin/lighthouse: Couldn't find a connected cluster or valid IPs for "nginx.nginx-test.svc.clusterset.local."
```

**How to reproduce it (as minimally and precisely as possible)**:
Just perform the userguide and scale down the deployment on of of the clusters to zero. Perform the curl command on the cluster with the scaled down deployment. Only install lighthouse agents and **no gateways!**

To get it working, apply this workaround on all clusters:

`kubectl delete crd gateways.submariner.io`

### PR DESCRIPTION
**Pull request by tpantelis**
Since the `gateways` CRD is always installed we need to also check for the existence of the `Submariner` resource to determine if the connectivity component is installed.

Fixes https://github.com/submariner-io/lighthouse/issues/936
Depends on https://github.com/submariner-io/subctl/pull/548

### CODE REVIEW

File: coredns/gateway/controller.go [hunk 1]
```diff
@@ -263,17 +264,36 @@ func (c *Controller) getClusterStatusMap() map[string]bool {
 	return c.clusterStatusMap.Load().(map[string]bool)
 }
 
-func (c *Controller) getCheckedClientset(kubeConfig *rest.Config) (dynamic.ResourceInterface, error) {
+func (c *Controller) getCheckedClientset(kubeConfig *rest.Config) (dynamic.ResourceInterface, bool, error) {
```
Comment (skitt) [inline coredns/gateway/controller.go]: We’ve said previously that we want to avoid adding boolean return values to represent information which is available elsewhere; in this instance, returning `false` implies returning a `nil` clientset.

**Review by skitt — CHANGES_REQUESTED** [review]

File: coredns/gateway/controller.go (hunk 1 above)
Comment (tpantelis) [reply coredns/gateway/controller.go]: But that means returning `nil, nil` in some cases which is not idiomatic, ie typically a nil error means the first return value is valid. Plus we have he `nilnil` linter which is intended to flag that but, after changing the code, it didn't. The other solution is to return an error indicating "not found". I'll do that.

**Review by skitt — APPROVED** [review]

**Review by dfarrell07 — APPROVED** [review]
